<?php
return [
    'tags' => [
        "Exams",
        "Testbanks",
        "Solution Manuals",
        "Exam Screenshots",
        "Study Resources",
        "Past Exams"
    ],
    'categories' => [
        [
            "title" => "Science & Technology",
            "categories" => [
                "Microbiology/Biology",
                "Environmental Science",
                "Computing Technology",
                "Anatomy & Physiology",
                "Information Technology",
                "Pediatric Primary",
                "Research Method",
                "Basic Chemistry",
                "Marine Biology",
                "Science Fiction",
                "Biochemistry",
                "Embryology",
                "Hematology",
                "Photography",
                "Philosophy",
                "Astronomy",
                "Pathology",
                "Biology",
                "Physics",
                "Maths",
                "Human Evolution"
            ],
        ],
        [
            "title" => "Business & Management",
            "categories" => [
                "Business",
                "Accounting",
                "Marketing",
                "Statistics",
                "Banking",
                "Management",
                "Personal Finance",
                "Employment law",
                "Financial Accounting",
                "Taxation of Business",
                "Business Statistics",
                "People Management",
            ],
        ],
        [
            "title" => "Humanities & Social Sciences",
            "categories" => [
                "Abnormal Child & Psychology",
                "Psychology",
                "Sociology",
                "Education Teaching",
                "Zoology",
                "Audiology",
                "Politics",
                "Geography",
                "Pathophysiology",
                "Religion",
                "Cinematography",
                "Abnormal Behavior",
            ],
        ],
        [
            "title" => "Sales & Marketing",
            "categories" => [
                "Creative Thinking",
                "Food & Culture",
                "Organizations",
                "Radiologic",
                "Music",
                "Mass Media",
                "Database",
                "Forecasting",
                "Adolescence",
                "Finance",
                "Data Analysis",
                "Discovering",
                "Investment",
                "Language",
            ],
        ],
        [
            "title" => "Health",
            "categories" => [
                "Nursing",
                "Pharmacology / Surgical",
                "Surgical Technology",
                "Health & Disease",
                "Blood Banking",
                "Medical",
                "Medicine",
                "Emergency Care",
                "Nutritional Care",
                "Dental Materials",
                "Cancer",
            ],
        ],
        [
            "title" => "Humanities",
            "categories" => [
                "Communication",
                "Economics",
                "Education",
                "History",
                "Human Development",
                "Human Physiology",
                "Human Sexuality",
                "Criminal Justic",
                "Living with Art",
                "Art",
                "Leadership",
                "Learning",
                "Legal Environment",
                "Lifespan",
                "Relationship",
            ],
        ],
        [
            "title" => "Other",
            "categories" => [
                "Understanding Dying",
                "Home Improvement",
                "Travel And Tourism",
                "Web Development",
                "Thriller & Suspense",
                "Illustrated Anatomy",
                "Social work",
                "Web Design",
                "Financial",
                "Essentials",
                "LPN to RN",
                "Auditing",
            ],
        ],
    ]
];
