<?php

return [
    'admin_email' => env('ADMIN_EMAIL', 'info@aceproctoredexams.com'),
    'admin_notifications_email' => env('ADMIN_NOTIFICATION_EMAIL', 'info@aceproctoredexams.com'),
    'super_admin_email' => env('SUPER_ADMIN_EMAIL', 'richard@qwconsultancy.com'),
    'whatsapp_number' => env('WHATSAPP_NUMBER', '+1832 861 8439'),
    'facebook_link' => env('FACEBOOK_LINK', 'https://www.facebook.com/share/g/18AfVXGQ5n/'),
    'school_type' => [
        "Preschool",
        "Elementary School",
        "Middle School",
        "High School",
        "Community College",
        "University",
        "Vocational/Technical School",
        "Graduate School",
        "Professional School (e.g., Law, Medical)",
        "Adult Education Center"
    ],
    'states' => [
        'us' => [
            "Alabama",
            "Alaska",
            "Arizona",
            "Arkansas",
            "California",
            "Colorado",
            "Connecticut",
            "Delaware",
            "Florida",
            "Georgia",
            "Hawaii",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "West Virginia",
            "Wisconsin",
            "Wyoming"
        ]
    ],
    'countries' => [
        'united-states-of-america' => 'United States of America',
        'canada' => "Canada"
    ]
];
